# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 71, 16))
        self.label_3.setObjectName("label_3")
        self.txtinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(140, 80, 421, 111))
        self.txtinfo.setObjectName("txtinfo")
        self.txtsignature = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsignature.setGeometry(QtCore.QRect(140, 300, 421, 111))
        self.txtsignature.setObjectName("txtsignature")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(140, 460, 75, 23))
        self.btnsign.setObjectName("btnsign")
        self.btnverify = QtWidgets.QPushButton(self.centralwidget)
        self.btnverify.setGeometry(QtCore.QRect(490, 460, 75, 23))
        self.btnverify.setObjectName("btnverify")
        self.btngenkey = QtWidgets.QPushButton(self.centralwidget)
        self.btngenkey.setGeometry(QtCore.QRect(430, 20, 75, 23))
        self.btngenkey.setObjectName("btngenkey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC"))
        self.label_2.setText(_translate("MainWindow", "INFO"))
        self.label_3.setText(_translate("MainWindow", "SIGNATURE"))
        self.btnsign.setText(_translate("MainWindow", "SIGN"))
        self.btnverify.setText(_translate("MainWindow", "VERIFY"))
        self.btngenkey.setText(_translate("MainWindow", "GENKEY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
